services:
  ticketing.seq:
     volumes:
       - ./.containers/seq:/data
     environment:
       - ACCEPT_EULA=Y
     ports:
       - 5341:5341
       - 9090:80
  ticketing.postgres:
    restart: always
    environment:
      - POSTGRES_USER=ticketing
      - POSTGRES_PASSWORD=MySecurePa$$w0rd
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
  